module.exports = {
  siteUrl: "https://sentrei.com",
  changefreq: "daily",
  priority: 0.7,
  sitemapSize: 5000,
  generateRobotsTxt: true,
  exclude: [
    "/create",
    "/dashboard",
    "/notifcations",
    "/profile",
    "/settings",
    "/ja/create",
    "/ja/dashboard",
    "/ja/notifcations",
    "/ja/profile",
    "/ja/settings",
    "/zh/create",
    "/zh/dashboard",
    "/zh/notifcations",
    "/zh/profile",
    "/zh/settings",
  ],
};
